{% raw %}---
- name: Ensure that supervisor is running
  service: name=supervisor state=started
  become_user: root
  become: true
  tags:
     - celery 

- name: Deploy the Celery worker startup Script
  template: src=celery.j2
            dest=/etc/supervisor/conf.d/celery.conf
            backup=yes
  become_user: root
  become: true
  tags:
     - celery

- name: Re-read the Supervisor config files
  command: supervisorctl reread
  become_user: root
  become: true
  tags:
     - celery

- name: Update Supervisor to add the app in the process group
  command: supervisorctl update
  become_user: root
  become: true
     - celery

- name: restart supervisor to ensure it picks up celery 
  service: name=supervisor state=restarted
  become_user: root
  become: true
  tags:
     - celery{% endraw %}
